In [16]:
import numpy as np

# code for calculating area of circle
# radii = np.array([1,2,3,4])
# print(np.pi * radii ** 2)

arr1 = np.array([[1,2,3]])
print(len(arr1))

arr2 = np.array([[4],[5],[3]])
print(arr1.shape)
print(arr2.shape)

print(arr1 * arr2)

mat = np.array([[1,2],
                [3,4]])

print(np.linalg.inv(mat))


1
(1, 3)
(3, 1)
[[ 4  8 12]
 [ 5 10 15]
 [ 3  6  9]]
[[-2.   1. ]
 [ 1.5 -0.5]]
