In [98]:
import numpy as np

rng = np.random.default_rng()

print(rng.integers(low = 1,high = 10,size = (3,3)))
print()

print(np.random.uniform(low = -1, high = 1))

fruits = np.array(["apple", "Banana", "coconut", "pineapple", "papaya"])
fruit = rng.choice(fruits)
print()

print(fruit)

[[9 6 2]
 [2 6 7]
 [6 7 7]]

-0.650774281430895

apple
