In [10]:
import numpy as np

arr1 = np.array([[1,2],
                 [3,4],
                 [5,6]])
print(arr1.ndim, arr1.shape)

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)   
print(a - b)   
print(a * b)   
print(b / a) 
print(a + 5)   
print(a * 2) 
print(a ** 2)
print(np.sqrt(a))  
print(np.exp(a))   
print(np.log(a))

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])     
print(arr[1:4])
print(arr[:3]) 
print(arr[::2])

mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(mat[0, 0])   # 1 (row 0, col 0)
print(mat[1, :])   # [4 5 6] (entire 2nd row)
print(mat[:, 2])   # [3 6 9] (entire 3rd column)
print(mat[:2, 1:])

arr2 = np.array([5, 10, 15, 20, 25])

print(arr2 > 10)         # [False False  True  True  True]
print(arr2[arr2 > 10])    # [15 20 25]
print(arr2[arr2 % 2 == 0])# [10 20] (even numbers)

2 (3, 2)
[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[6 7 8 9]
[2 4 6 8]
[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
10
50
[20 30 40]
[10 20 30]
[10 30 50]
1
[4 5 6]
[3 6 9]
[[2 3]
 [5 6]]
[False False  True  True  True]
[15 20 25]
[10 20]
